### ISSUE TITLE
Netifaces (0.11.0) refuses to install during pdm install using python 3.10.2 or python 3.11.4

### ISSUE THREAD

**Issue by Kzhanok** [raoulg/ML22#3]
During initialization of the environment (with 3.10.2) using pdm init or pdm install command an error pops up that states "Microsoft Visual C++ 14.0 is required". Visual CPP build tools was installed but did not resolve the issue during installation.
Using Python 3.11.4 further complicates the install, since pyarrow cannot install alongside netifaces.

Netifaces compiles during installation and the suggested fix is:
"https://stackoverflow.com/questions/48541801/microsoft-visual-c-14-0-is-required-get-it-with-microsoft-visual-c-build-t"

I have not yet attempted to use the python development install before running the pdm install command.
Will return and update this issue if succesfull.

This is a Windows 11 related issue, using a linux environment no issues were found.

I have not yet attempted to use the python development.
Will return and update this issue if succesfull.

**Comment by raoulg** [comment]
The issue here seems to be that you dont have c++ make tools installed.
I'm not sure if you can install that from inside VS code, this https://stackoverflow.com/questions/62441296/install-cmake-tools-after-visual-studio-already-installed seems to suggest you can but I have no Windows machine to test it.

I dont expect switching python versions or dependency managers here to be the issue.

In addition to that: please note that this repository is not guaranteed to function on windows, mainly because of the issues people have with the ray tune library. It works sorta, sometimes, but a lot of people have issues with ray.

**Comment by Kzhanok** [comment]
Installing Python development kit from the visual code installer resolves this issue. Originates from netifaces trying to compile a C++ build for the package which requires that package. See image below for reference (https://visualstudio.microsoft.com/downloads/)
![image](https://github.com/user-attachments/assets/f53bebf9-cefc-45d9-87ca-2573b7571927)

**Comment by raoulg** [comment]
The netifaces package was a dependency from hpbandster, which was a dependency from ray tune when you wanted to run BOHB. However, both hpbandster and netifaces are deprecated. Because of that, I removed the dependency and I will look for a replacement
